Vagrant.configure("2") do |config|
  #Public Configuration
  config.vm.box = "debian/bookworm64"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  #Machine Configuration
  config.vm.define "vagrant-shell" do |lab|
    lab.vm.hostname = "container-host"
    lab.vm.network "private_network", type: "static", ip: "192.168.121.111", auto_config: false
    lab.vm.provider "libvirt" do |v|
      v.memory = 2048
      v.cpus = 2
  #config.vm.provision "shell", path: "install_containerd.sh"
    end
  end
end

