Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.provider "libvirt"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  nodes = [
    { type: "controller", count: 3, base_ip: 3, memory: 1024, cpus: 1 },
    { type: "haproxy", count: 2, base_ip: 6, memory: 1024, cpus: 2 },
    { type: "worker", count: 3, base_ip: 8, memory: 2048, cpus: 2 }
  ]

  nodes.each do |group|
    (1..group[:count]).each do |i|
      config.vm.define "#{group[:type]}#{i}.k8s.local" do |node|
        node.vm.network "private_network", ip: "192.168.121.#{group[:base_ip] + i - 1}"
        node.vm.hostname = "#{group[:type]}#{i}.k8s.local"

        node.vm.provider "libvirt" do |lv|
          lv.memory = group[:memory]
          lv.cpus = group[:cpus]
        end
      end
    end
  end
end

