Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.provider "libvirt"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Loop for 3 controllers
  (1..3).each do |i|
    config.vm.define "controller#{i}.k8s.local" do |controller|
      ip = "192.168.121.#{i + 2}"
      controller.vm.network "private_network", ip: ip
      controller.vm.hostname = "controller#{i}.k8s.local"

      controller.vm.provider "libvirt" do |lv|
        lv.memory = 1024
        lv.cpus = 1
      end
    end
  end

  # Loop for 2 HAProxy nodes
  (1..2).each do |i|
    config.vm.define "haproxy#{i}.k8s.local" do |haproxy|
      ip = "192.168.121.#{i + 5}"
      haproxy.vm.network "private_network", ip: ip
      haproxy.vm.hostname = "haproxy#{i}.k8s.local"

      haproxy.vm.provider "libvirt" do |lv|
        lv.memory = 1024
        lv.cpus = 2
      end
    end
  end

  # Loop for 3 worker nodes
  (1..3).each do |i|
    config.vm.define "worker#{i}.k8s.local" do |worker|
      ip = "192.168.121.#{i + 7}"
      worker.vm.network "private_network", ip: ip
      worker.vm.hostname = "worker#{i}.k8s.local"

      worker.vm.provider "libvirt" do |lv|
        lv.memory = 2048
        lv.cpus = 2
      end
    end
  end
end

