Vagrant.configure("2") do |config|
  #Public Configuration
  config.vm.box = "debian/bookworm64"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  #Machine Configuration
  config.vm.define "vagrant-lab1" do |lab|
    lab.vm.hostname = "my-lab"
    lab.vm.network "private_network", ip: "192.168.121.110"
    lab.vm.provider "libvirt" do |v|
      v.memory = 2048
      v.cpus = 2
    end
  end
end

